name: Upload Assets

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Load secrets
      id: load-credentials
      uses: 1password/load-secrets-action@v1.2.0
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        AWS_ACCESS_KEY_ID: op://CI-CD/AWS_ACCESS_KEY_ID/credential
        AWS_SECRET_KEY: op://CI-CD/AWS_SECRET_KEY/credential

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
        aws-region: 'eu-central-1'

    - name: Upload assets to s3
      run: aws s3 sync trade-frontend-assets/ s3://trade-frontend-assets --delete

    - name: Invalidate Cloudfront distribution
      run: aws cloudfront create-invalidation --distribution-id E9N0UEUZ836RV --paths "/*"

    - name: List s3
      run: aws s3 ls s3://trade-frontend-assets