name: Upload Assets

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
        aws-region: 'eu-central-1'
    # - uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --delete
    #   env:
    #     AWS_S3_BUCKET: 'sergey-test-assets'
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
    #     SOURCE_DIR: 'trade-frontend-assets'      # optional: defaults to entire repositorys
    - name: Upload assets to s3
      run: aws s3 sync trade-frontend-assets/ s3://trade-frontend-assets    
    - name: List s3
      run: aws s3 ls s3://trade-frontend-assets