name: Upload Assets

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@master
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
        aws-region: 'eu-central-1'

    - name: Upload assets to s3
      run: aws s3 sync trade-frontend-assets/ s3://trade-frontend-assets --delete

    - name: Invalidate Cloudfront distribution
      run: aws cloudfront create-invalidation --distribution-id E9N0UEUZ836RV --paths "/*"

    - name: List s3
      run: aws s3 ls s3://trade-frontend-assets